
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naheen
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        pappu = new javax.swing.JPasswordField();
        regPasstxt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        regUsertxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        box22 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        box11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gappu = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        FullBackground = new javax.swing.JLabel();
        regCpasstxt2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setLayout(null);

        register.setBackground(new java.awt.Color(165, 55, 253));
        register.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel7.add(register);
        register.setBounds(510, 520, 95, 31);

        pappu.setBackground(new java.awt.Color(220, 198, 224));
        pappu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pappuActionPerformed(evt);
            }
        });
        jPanel7.add(pappu);
        pappu.setBounds(550, 440, 160, 20);

        regPasstxt.setBackground(new java.awt.Color(220, 198, 224));
        jPanel7.add(regPasstxt);
        regPasstxt.setBounds(550, 400, 163, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password :");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(410, 440, 121, 17);

        regUsertxt.setBackground(new java.awt.Color(220, 198, 224));
        regUsertxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel7.add(regUsertxt);
        regUsertxt.setBounds(550, 360, 165, 23);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Password               :");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(410, 400, 121, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("User                      : ");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(410, 360, 125, 17);

        login.setBackground(new java.awt.Color(165, 55, 253));
        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setText("Log in");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel7.add(login);
        login.setBounds(110, 500, 83, 31);

        box22.setBackground(new java.awt.Color(220, 198, 224));
        box22.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel7.add(box22);
        box22.setBounds(160, 430, 183, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Password    :");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(20, 430, 130, 28);

        box11.setBackground(new java.awt.Color(220, 198, 224));
        box11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel7.add(box11);
        box11.setBounds(160, 380, 183, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Username   : ");
        jPanel7.add(jLabel2);
        jLabel2.setBounds(20, 380, 135, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jLabel1.setText("  ");
        jPanel7.add(jLabel1);
        jLabel1.setBounds(260, 100, 252, 200);

        gappu.setBackground(new java.awt.Color(220, 198, 224));
        jPanel7.add(gappu);
        gappu.setBounds(590, 480, 120, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Admin approval code:");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(410, 480, 140, 17);

        FullBackground.setBackground(new java.awt.Color(220, 198, 224));
        jPanel7.add(FullBackground);
        FullBackground.setBounds(-10, -20, 750, 660);

        regCpasstxt2.setBackground(new java.awt.Color(220, 198, 224));
        jPanel7.add(regCpasstxt2);
        regCpasstxt2.setBounds(550, 440, 163, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        ArrayList<String> username=new ArrayList<>();
    
        ArrayList<String> password=new ArrayList<>();
    public void usp(){
        
        username.add("admin");
        password.add("12345");
    }
    int d=0;
    
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       if(d==0){
           usp();
           d++;
       }
       String ss=box11.getText();
       String s11=box22.getText();
       int count=0,lol=0;
       for(String w:username){
           if(ss.equals(w)){
               count=1;
           

           
       }//else{     
           //JOptionPane.showMessageDialog(this, "Invalid Username/Password");     
       //}
       }
       
       for(String ww:password){
           if(s11.equals(ww)){
               lol=1;
           }
       }
       if(count==1 && lol==1){
           //JOptionPane.showMessageDialog(this, "Successfully Logged In");
           close();
           Hackers_Cafe njf=new Hackers_Cafe();
           
           njf.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(this, "Invalid Username/Password");
       }
       
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String s1=regUsertxt.getText();
        String s2=regPasstxt.getText();
        String s3=pappu.getText();
        String s4=gappu.getText();
        
        if(s1.isEmpty() && s2.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please FILL UP all field.");
        }else{
            
            if(s2.length()>=4){
                if(s2.equals(s3)){
                    if(s4.equals("13579")){
                    username.add(s1);
                    password.add(s2);
                    regUsertxt.setText("");
                    regPasstxt.setText("");
                    pappu.setText("");
                    
                    JOptionPane.showMessageDialog(this, "Successfully Registered !!");
                    }else{
                        JOptionPane.showMessageDialog(this, "Admin Approval Not Correct.");
                    }
                    
            
                }else{
                    JOptionPane.showMessageDialog(this, "Please Recheck CONFIRM PASSWORD field.");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Password length must be 4 characters");
            }
            
        }
        
        
        
    }//GEN-LAST:event_registerActionPerformed

    private void pappuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pappuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pappuActionPerformed

    
    public void close(){
        WindowEvent winclose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FullBackground;
    private javax.swing.JTextField box11;
    private javax.swing.JPasswordField box22;
    private javax.swing.JPasswordField gappu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pappu;
    private javax.swing.JPasswordField regCpasstxt2;
    private javax.swing.JPasswordField regPasstxt;
    private javax.swing.JTextField regUsertxt;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
